name: backend-test
on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DB_HOST: 127.0.0.1
      DB_USER: postgres
      DB_PASS: postgres
      DB_DB: postgres
      DB_PORT: 5432
      MINIO_HOST: localhost
      MINIO_PORT: 9000
      MINIO_SSL: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
      - name: Migrate Database
        working-directory: backend
        run: touch .env && task db-reset -y
      - name: Run Tests
        working-directory: backend
        run: go test -p 1 ./...